// Generated file - do not edit!
// Source: html/portal.html

#ifndef GENERATED_HTML_PORTAL_H
#define GENERATED_HTML_PORTAL_H

#include <pgmspace.h>

static const char PORTAL_HTML[] PROGMEM = "<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>ESP32 WiFi Setup</title>\n"
"    <style>\n"
"        body { \n"
"            font-family: Arial, sans-serif; \n"
"            margin: 0; \n"
"            padding: 0; \n"
"            background-color: #f5f5f5; \n"
"            color: #333; \n"
"        }\n"
"        .container { \n"
"            max-width: 800px; \n"
"            margin: 20px auto; \n"
"            padding: 20px; \n"
"            background-color: white; \n"
"            border-radius: 5px; \n"
"            box-shadow: 0 2px 5px rgba(0,0,0,0.1); \n"
"        }\n"
"        h1, h2 { color: #0066cc; }\n"
"        .header { \n"
"            background-color: #0066cc; \n"
"            color: white; \n"
"            padding: 10px 20px; \n"
"            text-align: center; \n"
"        }\n"
"        .form-group { margin-bottom: 15px; }\n"
"        label { \n"
"            display: block; \n"
"            margin-bottom: 5px; \n"
"            font-weight: bold; \n"
"        }\n"
"        input[type='text'], input[type='password'], select { \n"
"            width: 100%; \n"
"            padding: 8px; \n"
"            border: 1px solid #ddd; \n"
"            border-radius: 4px; \n"
"            box-sizing: border-box; \n"
"        }\n"
"        .button-container { \n"
"            margin-top: 15px; \n"
"            text-align: center; \n"
"        }\n"
"        .button { \n"
"            display: inline-block; \n"
"            padding: 10px 20px; \n"
"            background-color: #0066cc; \n"
"            color: white; \n"
"            text-decoration: none; \n"
"            border-radius: 4px; \n"
"            border: none; \n"
"            cursor: pointer; \n"
"        }\n"
"        .button.secondary { background-color: #777; }\n"
"        .button:hover { background-color: #0055aa; }\n"
"        .button.secondary:hover { background-color: #666; }\n"
"        footer { \n"
"            text-align: center; \n"
"            margin-top: 20px; \n"
"            color: #777; \n"
"            font-size: 0.8em; \n"
"        }\n"
"        .network-list {\n"
"            max-height: 200px;\n"
"            overflow-y: auto;\n"
"            border: 1px solid #ddd;\n"
"            border-radius: 4px;\n"
"            margin-bottom: 15px;\n"
"        }\n"
"        .network-item {\n"
"            padding: 8px 15px;\n"
"            border-bottom: 1px solid #eee;\n"
"            cursor: pointer;\n"
"        }\n"
"        .network-item:hover {\n"
"            background-color: #f5f5f5;\n"
"        }\n"
"        .network-item.selected {\n"
"            background-color: #e0f0ff;\n"
"        }\n"
"        .signal-strength {\n"
"            float: right;\n"
"            font-size: 0.8em;\n"
"            color: #666;\n"
"        }\n"
"        .lock-icon {\n"
"            margin-left: 5px;\n"
"        }\n"
"        .success-icon {\n"
"            color: #28a745;\n"
"            font-size: 48px;\n"
"            text-align: center;\n"
"            margin: 20px 0;\n"
"        }\n"
"        .progress {\n"
"            height: 4px;\n"
"            background-color: #e9ecef;\n"
"            border-radius: 2px;\n"
"            margin: 20px 0;\n"
"            overflow: hidden;\n"
"        }\n"
"        .progress-bar {\n"
"            height: 100%;\n"
"            background-color: #0066cc;\n"
"            width: 0%;\n"
"            transition: width 10s linear;\n"
"        }\n"
"        .hidden {\n"
"            display: none;\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"header\">\n"
"        <h1 id=\"page-title\">ESP32 WiFi Setup</h1>\n"
"    </div>\n"
"    \n"
"    <!-- Home Screen -->\n"
"    <div id=\"home-screen\" class=\"container\">\n"
"        <h2>Welcome to ESP32 WiFi Setup</h2>\n"
"        <p>This portal allows you to configure your device's WiFi connection.</p>\n"
"        <p>Click the button below to scan for available networks and set up your WiFi connection.</p>\n"
"        \n"
"        <div class=\"button-container\">\n"
"            <a href=\"javascript:showScreen('config-screen')\" class=\"button\">Configure WiFi</a>\n"
"        </div>\n"
"    </div>\n"
"    \n"
"    <!-- Configuration Screen -->\n"
"    <div id=\"config-screen\" class=\"container hidden\">\n"
"        <h2>Configure WiFi Connection</h2>\n"
"        <p>Please select your WiFi network and enter the password if required.</p>\n"
"        \n"
"        <form id=\"wifi-form\" onsubmit=\"return saveWifiConfig()\">\n"
"            <div class=\"form-group\">\n"
"                <label for=\"ssid\">WiFi Network:</label>\n"
"                <select name=\"ssid\" id=\"ssid\" required>\n"
"                    <!-- NETWORK_LIST_PLACEHOLDER -->\n"
"                </select>\n"
"            </div>\n"
"            \n"
"            <div class=\"form-group\">\n"
"                <label for=\"password\">Password:</label>\n"
"                <input type=\"password\" name=\"password\" id=\"password\">\n"
"            </div>\n"
"            \n"
"            <div class=\"button-container\">\n"
"                <button type=\"submit\" class=\"button\">Save Configuration</button>\n"
"            </div>\n"
"        </form>\n"
"        \n"
"        <div class=\"button-container\" style=\"margin-top: 20px;\">\n"
"            <a href=\"javascript:refreshNetworks()\" class=\"button secondary\">Refresh Network List</a>\n"
"            <a href=\"javascript:showScreen('home-screen')\" class=\"button secondary\">Back</a>\n"
"        </div>\n"
"    </div>\n"
"    \n"
"    <!-- Success Screen -->\n"
"    <div id=\"success-screen\" class=\"container hidden\">\n"
"        <div class=\"success-icon\">✓</div>\n"
"        <h2>WiFi Configuration Saved</h2>\n"
"        <p>The device will now attempt to connect to the WiFi network.</p>\n"
"        <p>If the connection is successful, the device will restart in normal mode.</p>\n"
"        <p>If the connection fails, the setup portal will be available again.</p>\n"
"        \n"
"        <div class=\"progress\">\n"
"            <div id=\"progress-bar\" class=\"progress-bar\"></div>\n"
"        </div>\n"
"        \n"
"        <p>Redirecting in <span id=\"countdown\">10</span> seconds...</p>\n"
"    </div>\n"
"    \n"
"    <!-- Error Screen -->\n"
"    <div id=\"error-screen\" class=\"container hidden\">\n"
"        <h2>Error Saving Configuration</h2>\n"
"        <p>There was an error saving your WiFi configuration.</p>\n"
"        <p>Please try again.</p>\n"
"        \n"
"        <div class=\"button-container\">\n"
"            <a href=\"javascript:showScreen('config-screen')\" class=\"button\">Back</a>\n"
"        </div>\n"
"    </div>\n"
"    \n"
"    <footer>&copy; 2024 ESP32 WiFi Setup</footer>\n"
"    \n"
"    <script>\n"
"        // Show the specified screen and hide others\n"
"        function showScreen(screenId) {\n"
"            const screens = ['home-screen', 'config-screen', 'success-screen', 'error-screen'];\n"
"            screens.forEach(id => {\n"
"                document.getElementById(id).classList.add('hidden');\n"
"            });\n"
"            document.getElementById(screenId).classList.remove('hidden');\n"
"            \n"
"            // Update page title\n"
"            let title = \"ESP32 WiFi Setup\";\n"
"            if (screenId === 'config-screen') title = \"WiFi Configuration\";\n"
"            else if (screenId === 'success-screen') title = \"WiFi Configuration Saved\";\n"
"            else if (screenId === 'error-screen') title = \"Configuration Error\";\n"
"            document.getElementById('page-title').textContent = title;\n"
"            \n"
"            // Start countdown if success screen\n"
"            if (screenId === 'success-screen') {\n"
"                startCountdown();\n"
"                document.getElementById('progress-bar').style.width = '100%';\n"
"            }\n"
"        }\n"
"        \n"
"        // Handle form submission\n"
"        function saveWifiConfig() {\n"
"            const form = document.getElementById('wifi-form');\n"
"            const formData = new FormData(form);\n"
"            \n"
"            fetch('/save-wifi', {\n"
"                method: 'POST',\n"
"                body: formData\n"
"            })\n"
"            .then(response => response.json())\n"
"            .then(data => {\n"
"                if (data.success) {\n"
"                    showScreen('success-screen');\n"
"                } else {\n"
"                    showScreen('error-screen');\n"
"                }\n"
"            })\n"
"            .catch(() => {\n"
"                showScreen('error-screen');\n"
"            });\n"
"            \n"
"            return false; // Prevent default form submission\n"
"        }\n"
"        \n"
"        // Refresh network list\n"
"        function refreshNetworks() {\n"
"            fetch('/scan-networks')\n"
"            .then(response => response.text())\n"
"            .then(html => {\n"
"                document.getElementById('ssid').innerHTML = html;\n"
"            });\n"
"        }\n"
"        \n"
"        // Start countdown on success screen\n"
"        function startCountdown() {\n"
"            let seconds = 10;\n"
"            const countdownEl = document.getElementById('countdown');\n"
"            \n"
"            const interval = setInterval(() => {\n"
"                seconds--;\n"
"                countdownEl.textContent = seconds;\n"
"                \n"
"                if (seconds <= 0) {\n"
"                    clearInterval(interval);\n"
"                    window.location.href = '/';\n"
"                }\n"
"            }, 1000);\n"
"        }\n"
"        \n"
"        // Initialize page\n"
"        document.addEventListener('DOMContentLoaded', function() {\n"
"            // Check if we need to show a specific screen based on URL hash\n"
"            const hash = window.location.hash.substr(1);\n"
"            if (hash && ['home-screen', 'config-screen', 'success-screen', 'error-screen'].includes(hash)) {\n"
"                showScreen(hash);\n"
"            }\n"
"        });\n"
"    </script>\n"
"</body>\n"
"</html>";

#endif // GENERATED_HTML_PORTAL_H
